export const moviesUrls = [
    { "url": "https://www.youtube.com/watch?v=NL9vG_f3MXc" },
    { "url": "https://www.youtube.com/watch?v=i16PlS9aTJU" },
    { "url": "https://www.youtube.com/watch?v=dyqaEs4YABs" },
    { "url": "https://www.youtube.com/watch?v=KUWn_TJTrnU" },
    { "url": "https://www.youtube.com/watch?v=fn3KWM1kuAw" },
    { "url": "https://www.youtube.com/watch?v=PiCbPlQ1CLU" },
    { "url": "https://www.youtube.com/watch?v=Z4aEH5xME08&t=21s" },
    { "url": "https://www.youtube.com/watch?v=T-H4nJQyMig" },
    { "url": "https://www.youtube.com/watch?v=LTroOdacWMU" },
    { "url": "https://www.youtube.com/watch?v=CAk9vqAINCc" },
    { "url": "https://www.youtube.com/watch?v=Tc0LU7y3btU" },
    { "url": "https://www.youtube.com/watch?v=_K-Gtb_ywfg" },
    { "url": "https://www.youtube.com/watch?v=vgXw0H-jhUg" },
    { "url": "https://youtu.be/UhRPEzpVoak" },
    { "url": "https://www.youtube.com/watch?v=lOVqbd8IE-w" },
    { "url": "https://www.youtube.com/watch?v=CwXOrWvPBPk" },
    { "url": "https://www.youtube.com/watch?v=eJHcsyNHktQ" },
    { "url": "https://www.youtube.com/watch?v=vgXw0H-jhUg" },
    { "url": "https://youtu.be/UhRPEzpVoak" },
    { "url": "https://www.youtube.com/watch?v=lOVqbd8IE-w" },
    { "url": "https://www.youtube.com/watch?v=CwXOrWvPBPk" },
    { "url": "https://www.youtube.com/watch?v=eJHcsyNHktQ" },
    { "url": "https://www.youtube.com/watch?v=T-H4nJQyMig" },
    { "url": "https://www.youtube.com/watch?v=LTroOdacWMU" },
    { "url": "https://www.youtube.com/watch?v=CAk9vqAINCc" }
]