import Head from 'next/head'
import { Navbar, Button, Modal } from '../components'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Cinemapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Button />
      <Modal />
    </div>
  )
}
