import Head from 'next/head'
import React, { useEffect } from 'react'
import { Navbar, Button, Modal } from '../components'
import { useDispatch } from 'react-redux'
import { fetchMovies } from '../redux/actions/moviesAction'


export default function Home() {
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(fetchMovies())
  }, [])

  return (
    <div>
      <Head>
        <title>Cinemapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Button />
      <Modal />
    </div>
  )
}
